name: Create or Update Repo

on:
    workflow_dispatch:
        inputs:
            repo_name:
                description: "Name of the repo to create"
                required: true
                type: string
            is_public_repo:
                description: If unchecked, repo is private
                required: true
                default: false
                type: boolean
            package-import-name:
                description: "Used in Imports"
                required: true
                type: string

jobs:
    create-repo-if-not-exists:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - env:
                  REPO_NAME: ${{ github.event.inputs.repo_name }}
                  GITHUB_USERNAME: cjknobla
                  IS_PUBLIC_REPO: ${{ github.event.inputs.is_public_repo }}
              run: |
                  bash run.sh create-repo-if-not-exists
    configure-repo:
        needs: [create-repo-if-not-exists]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - run: |
                  bash run.sh configure-repo
              env:
                  TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
                  PROD_PYPI_TOKEN: ${{ secrets.PROD_PYPI_TOKEN }}
                  REPO_NAME: ${{ github.event.inputs.repo_name }}
                  GITHUB_USERNAME: cjknobla

    open-pr-with-generated-project:
        needs: [create-repo-if-not-exists]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - run: |
                  bash run.sh open-pr-with-generated-project
              env:
                  REPO_NAME: ${{ github.event.inputs.repo_name }}
                  GITHUB_USERNAME: cjknobla
                  PACKAGE_IMPORT_NAME: ${{ github.event.inputs.package-import-name }}
